"use client";

import React, { createContext, useState, useContext } from "react";

const EventsContext = createContext();

export const useEvents = () => useContext(EventsContext);

export const EventsProvider = ({ children }) => {
  const initialEvents = [
    {
      nombre: "Conferencia Anual de Tecnología",
      numeroEdicion: "10",
      descripcion:
        "El evento más importante del año para profesionales de la tecnología.",
      type: "Corporativos",
      subtype: "Conferencia",
      origen: "Empresarial",
      tema: "Tecnologia",
      frecuencia: "Anual",
      tipoRotacion: "Nacional",
      mesasCoffeeBreak: true,
      cateringAlmuerzo: true,
      cateringCena: false,
      paquetePreEvento: false,
      paquetePostEvento: false,
      sede: "Hotel Hilton",
      ciudad: "Buenos Aires",
      salonesUtilizados:
        "Salón Principal, Sala de Reuniones A, Sala de Workshops",
      mapsUrl: "https://maps.app.goo.gl/...",
      ultimaSedeAnterior: "Hotel Sheraton",
      proximaSede: "Hotel Marriott",
      dateTimes: [
        {
          fechaDesde: "2025-05-20",
          fechaHasta: "2025-05-20",
          horaDesde: "09:00",
          horaHasta: "18:00",
        },
        {
          fechaDesde: "2025-05-21",
          fechaHasta: "2025-05-21",
          horaDesde: "09:00",
          horaHasta: "18:00",
        },
        {
          fechaDesde: "2025-05-22",
          fechaHasta: "2025-05-22",
          horaDesde: "09:00",
          horaHasta: "18:00",
        },
      ],
      estimatedAttendance: { local: "500", national: "200", foreign: "50" },
      virtualTransmission: true,
      transmissionLink: "https://live.conferenciatech.com",
      producer: "Eventos Digitales Inc.",
      website: "https://www.conferenciatech.com",
      logo: "logo_conferencia_tech.png",
      // image: "imagen_conferencia_tech.jpg",
      responsiveImage: "responsive_conferencia_tech.jpg",
    },
    {
      nombre: "Partido de Fútbol Amistoso - Veteranos",
      numeroEdicion: "N/A",
      descripcion: "Encuentro recreativo entre equipos de veteranos locales.",
      type: "Deporte",
      subtype: "Partido",
      origen: "Asociativo / Sin fines de lucro",
      tema: "Deporte",
      frecuencia: "Irregular",
      tipoRotacion: "Local",
      mesasCoffeeBreak: false,
      cateringAlmuerzo: false,
      cateringCena: false,
      paquetePreEvento: false,
      paquetePostEvento: false,
      sede: "Club Deportivo Norte",
      ciudad: "San Miguel de Tucumán",
      salonesUtilizados: "Cancha Principal",
      mapsUrl: "https://maps.app.goo.gl/...",
      ultimaSedeAnterior: "Club Atlético Sur",
      proximaSede: false,
      dateTimes: [
        {
          fechaDesde: "2025-05-25",
          fechaHasta: "2025-05-25",
          horaDesde: "10:00",
          horaHasta: "12:00",
        },
      ],
      estimatedAttendance: { local: "100", national: "0", foreign: "0" },
      virtualTransmission: false,
      transmissionLink: false,
      producer: false,
      website: false,
      logo: "logo_club_deportivo.png",
      // image: "imagen_partido_futbol.jpg",
      responsiveImage: "responsive_partido_futbol.jpg",
    },
    {
      nombre: "Feria del Libro de Buenos Aires",
      numeroEdicion: "49",
      descripcion:
        "Uno de los eventos literarios más importantes de Latinoamérica.",
      type: "Cultura",
      subtype: "Feria",
      origen: "Empresarial",
      tema: "Literatura",
      frecuencia: "Anual",
      tipoRotacion: "Nacional",
      mesasCoffeeBreak: true,
      cateringAlmuerzo: true,
      cateringCena: false,
      paquetePreEvento: true,
      paquetePostEvento: true,
      sede: "La Rural Predio Ferial",
      ciudad: "Buenos Aires",
      salonesUtilizados: "Pabellones, Salas de Conferencias",
      mapsUrl: "https://maps.app.goo.gl/...",
      ultimaSedeAnterior: "La Rural Predio Ferial",
      proximaSede: "La Rural Predio Ferial",
      dateTimes: [
        {
          fechaDesde: "2025-05-05",
          fechaHasta: "2025-05-05",
          horaDesde: "15:00",
          horaHasta: "18:00",
        },
        {
          fechaDesde: "2025-05-12",
          fechaHasta: "2025-05-12",
          horaDesde: "15:00",
          horaHasta: "18:00",
        },
        {
          fechaDesde: "2025-05-19",
          fechaHasta: "2025-05-19",
          horaDesde: "15:00",
          horaHasta: "18:00",
        },
        {
          fechaDesde: "2025-05-26",
          fechaHasta: "2025-05-26",
          horaDesde: "15:00",
          horaHasta: "18:00",
        },
      ],
      estimatedAttendance: {
        local: "50000",
        national: "20000",
        foreign: "5000",
      },
      virtualTransmission: true,
      transmissionLink: "https://live.feriadellibro.com.ar",
      producer: "Fundación El Libro",
      website: "https://www.feriadellibro.com.ar",
      logo: "logo_feria_libro.png",
      image: "/carrouselEvents/feriadellibro.png",
      responsiveImage: "responsive_feria_libro.jpg",
    },
    {
      nombre: "Congreso Internacional de Cardiología",
      numeroEdicion: "XXV",
      descripcion:
        "Evento anual que reúne a los principales expertos en cardiología para discutir los últimos avances y tratamientos.",
      type: "Asociativos",
      subtype: "Congreso",
      origen: "Academico",
      tema: "Medicina",
      frecuencia: "Anual",
      tipoRotacion: "Internacional - Panamerica",
      mesasCoffeeBreak: true,
      cateringAlmuerzo: true,
      cateringCena: false,
      paquetePreEvento: true,
      paquetePostEvento: true,
      sede: "Centro de Convenciones de Buenos Aires",
      ciudad: "Buenos Aires",
      salonesUtilizados: "Salón Plenario, Salas 1-5",
      mapsUrl: "https://maps.app.goo.gl/example1",
      ultimaSedeAnterior: "Ciudad de México",
      proximaSede: "Sao Paulo",
      dateTimes: [
        {
          fechaDesde: "2025-05-05",
          fechaHasta: "2025-05-05",
          horaDesde: "09:00",
          horaHasta: "18:00",
        },
        {
          fechaDesde: "2025-05-06",
          fechaHasta: "2025-05-06",
          horaDesde: "09:00",
          horaHasta: "18:00",
        },
        {
          fechaDesde: "2025-05-07",
          fechaHasta: "2025-05-07",
          horaDesde: "09:00",
          horaHasta: "18:00",
        },
        {
          fechaDesde: "2025-05-08",
          fechaHasta: "2025-05-08",
          horaDesde: "09:00",
          horaHasta: "18:00",
        },
      ],
      estimatedAttendance: { local: "1500", national: "500", foreign: "300" },
      virtualTransmission: true,
      transmissionLink: "https://live.cardiologia.org",
      producer: "",
      website: "https://cardiologia.org/congreso2025",
      logo: "logo_cardiologia.png",
      image: "/carrouselEvents/cidc.png",
      responsiveImage: "imagen_congreso_cardio_responsive.jpg",
    },
    {
      nombre: "Taller de Marketing Digital para Emprendedores",
      numeroEdicion: "3",
      descripcion:
        "Taller intensivo de dos días enfocado en estrategias de marketing digital para pequeñas empresas.",
      type: "Corporativos",
      subtype: "Capacitación",
      origen: "Empresarial",
      tema: "Management / Negocios",
      frecuencia: "Semestral",
      tipoRotacion: "Local",
      mesasCoffeeBreak: true,
      cateringAlmuerzo: true,
      cateringCena: false,
      paquetePreEvento: false,
      paquetePostEvento: false,
      sede: "Espacio Coworking Tucumán",
      ciudad: "San Miguel de Tucumán",
      salonesUtilizados: "Sala Principal",
      mapsUrl: "https://maps.app.goo.gl/example2",
      ultimaSedeAnterior: "Espacio Coworking Tucumán",
      proximaSede: "Espacio Coworking Tucumán",
      dateTimes: [
        {
          fechaDesde: "2025-05-10",
          fechaHasta: "2025-05-10",
          horaDesde: "10:00",
          horaHasta: "17:00",
        },
        {
          fechaDesde: "2025-05-11",
          fechaHasta: "2025-05-11",
          horaDesde: "10:00",
          horaHasta: "17:00",
        },
      ],
      estimatedAttendance: { local: "50", national: "0", foreign: "0" },
      virtualTransmission: false,
      transmissionLink: null,
      producer: "Agencia Digital XYZ",
      website: "https://agenciaxyz.com/taller-marketing",
      logo: "logo_agenciaxyz.png",
      image: "/carrouselEvents/tmde.jpg",
      responsiveImage: "imagen_taller_marketing_responsive.jpg",
    },
    {
      nombre: "Festival de Cine Independiente",
      numeroEdicion: "15",
      descripcion:
        "Muestra anual de películas independientes de directores nacionales e internacionales.",
      type: "Cultura",
      subtype: "Festival",
      origen: "Asociativo / Sin fines de lucro",
      tema: "Cultura",
      frecuencia: "Anual",
      tipoRotacion: "Nacional",
      mesasCoffeeBreak: true,
      cateringAlmuerzo: false,
      cateringCena: true,
      paquetePreEvento: false,
      paquetePostEvento: false,
      sede: "Cine Teatro Plaza",
      ciudad: "Mendoza",
      salonesUtilizados: "Sala 1, Sala 2",
      mapsUrl: "https://maps.app.goo.gl/example3",
      ultimaSedeAnterior: "Mendoza",
      proximaSede: "Mendoza",
      dateTimes: [
        {
          fechaDesde: "2025-05-15",
          fechaHasta: "2025-05-15",
          horaDesde: "18:00",
          horaHasta: "23:00",
        },
        {
          fechaDesde: "2025-05-16",
          fechaHasta: "2025-05-16",
          horaDesde: "18:00",
          horaHasta: "23:00",
        },
        {
          fechaDesde: "2025-05-17",
          fechaHasta: "2025-05-17",
          horaDesde: "18:00",
          horaHasta: "23:00",
        },
        {
          fechaDesde: "2025-05-18",
          fechaHasta: "2025-05-18",
          horaDesde: "18:00",
          horaHasta: "23:00",
        },
        {
          fechaDesde: "2025-05-19",
          fechaHasta: "2025-05-19",
          horaDesde: "18:00",
          horaHasta: "23:00",
        },
        {
          fechaDesde: "2025-05-20",
          fechaHasta: "2025-05-20",
          horaDesde: "18:00",
          horaHasta: "23:00",
        },
      ],
      estimatedAttendance: { local: "300", national: "100", foreign: "20" },
      virtualTransmission: true,
      transmissionLink: "https://festivaldecine.com/live",
      producer: "Asociación de Cineastas Independientes",
      website: "https://festivaldecine.com",
      logo: "logo_festival_cine.png",
      // image: "imagen_festival_cine.jpg",
      responsiveImage: "// imagen_festival_cine_responsive.jpg",
    },
    {
      nombre: "Seminario de Inteligencia Artificial",
      numeroEdicion: "II",
      descripcion:
        "Seminario avanzado sobre las últimas tendencias y aplicaciones de la inteligencia artificial.",
      type: "Académico",
      subtype: "Seminario",
      origen: "Academico",
      tema: "Tecnologia",
      frecuencia: "Anual",
      tipoRotacion: "Regional",
      mesasCoffeeBreak: true,
      cateringAlmuerzo: true,
      cateringCena: false,
      paquetePreEvento: false,
      paquetePostEvento: false,
      sede: "Universidad Nacional de Córdoba",
      ciudad: "Córdoba",
      salonesUtilizados: "Aula Magna",
      mapsUrl: "https://maps.app.goo.gl/example4",
      ultimaSedeAnterior: "Rosario",
      proximaSede: "Santa Fe",
      dateTimes: [
        {
          fechaDesde: "2025-05-22",
          fechaHasta: "2025-05-22",
          horaDesde: "09:30",
          horaHasta: "17:30",
        },
        {
          fechaDesde: "2025-05-23",
          fechaHasta: "2025-05-23",
          horaDesde: "09:30",
          horaHasta: "17:30",
        },
        {
          fechaDesde: "2025-05-24",
          fechaHasta: "2025-05-24",
          horaDesde: "09:30",
          horaHasta: "17:30",
        },
      ],
      estimatedAttendance: { local: "200", national: "50", foreign: "10" },
      virtualTransmission: true,
      transmissionLink: "https://unccba.edu.ar/seminario-ia",
      producer: "Facultad de Informática",
      website: "https://unccba.edu.ar/seminario-ia",
      logo: "logo_unccba.png",
      // image: "imagen_seminario_ia.jpg",
      responsiveImage: "imagen_seminario_ia_responsive.jpg",
    },
    {
      nombre: "Partido de Fútbol Liga Profesional",
      numeroEdicion: null,
      descripcion:
        "Partido correspondiente a la fecha de la Liga Profesional de Fútbol Argentino.",
      type: "Deporte",
      subtype: "Partido",
      origen: "Empresarial",
      tema: "Deporte",
      frecuencia: "Irregular",
      tipoRotacion: "Nacional",
      mesasCoffeeBreak: false,
      cateringAlmuerzo: false,
      cateringCena: false,
      paquetePreEvento: false,
      paquetePostEvento: false,
      sede: "Estadio Monumental",
      ciudad: "Buenos Aires",
      salonesUtilizados: null,
      mapsUrl: "https://maps.app.goo.gl/example5",
      ultimaSedeAnterior: null,
      proximaSede: null,
      dateTimes: [
        {
          fechaDesde: "2025-05-18",
          fechaHasta: "2025-05-18",
          horaDesde: "18:00",
          horaHasta: "20:00",
        },
      ],
      estimatedAttendance: { local: "70000", national: "5000", foreign: "100" },
      virtualTransmission: true,
      transmissionLink: "https://tntsports.com.ar/live",
      producer: "Liga Profesional de Fútbol",
      website: "https://ligaprofesional.com.ar",
      logo: "logo_liga_profesional.png",
      // image: "// imagen_partido_futbol.jpg",
      responsiveImage: "imagen_partido_futbol_responsive.jpg",
    },
    {
      nombre: "Conferencia Anual de Recursos Humanos",
      numeroEdicion: "X",
      descripcion:
        "Evento para profesionales de recursos humanos con ponencias y talleres sobre las últimas tendencias del sector.",
      type: "Corporativos",
      subtype: "Conferencia",
      origen: "Empresarial",
      tema: "Management / Negocios",
      frecuencia: "Anual",
      tipoRotacion: "Nacional",
      mesasCoffeeBreak: true,
      cateringAlmuerzo: true,
      cateringCena: false,
      paquetePreEvento: false,
      paquetePostEvento: false,
      sede: "Hotel Hilton",
      ciudad: "Rosario",
      salonesUtilizados: "Salón Ballroom, Salas de Reuniones A y B",
      mapsUrl: "https://maps.app.goo.gl/example6",
      ultimaSedeAnterior: "Buenos Aires",
      proximaSede: "Córdoba",
      dateTimes: [
        {
          fechaDesde: "2025-05-27",
          fechaHasta: "2025-05-27",
          horaDesde: "09:00",
          horaHasta: "17:00",
        },
      ],
      dateTimes: [
        {
          fechaDesde: "2025-05-28",
          fechaHasta: "2025-05-28",
          horaDesde: "09:00",
          horaHasta: "17:00",
        },
      ],
      estimatedAttendance: { local: "400", national: "150", foreign: "30" },
      virtualTransmission: false,
      transmissionLink: null,
      producer: "Consultora RH Global",
      website: "https://conferenciarh.com.ar",
      logo: "logo_rhglobal.png",
      // image: "imagen_conferencia_rh.jpg",
      responsiveImage: "imagen_conferencia_rh_responsive.jpg",
    },
    {
      nombre: "Obra de Teatro: La Comedia Final",
      numeroEdicion: null,
      descripcion:
        "Presentación de la aclamada obra de teatro 'La Comedia Final'.",
      type: "Cultura",
      subtype: "Obra de Teatro",
      origen: "Asociativo / Sin fines de lucro",
      tema: "Arte y desenio",
      frecuencia: "Irregular",
      tipoRotacion: "Provincial",
      mesasCoffeeBreak: false,
      cateringAlmuerzo: false,
      cateringCena: false,
      paquetePreEvento: false,
      paquetePostEvento: false,
      sede: "Teatro Independencia",
      ciudad: "Mendoza",
      salonesUtilizados: "Sala Principal",
      mapsUrl: "https://maps.app.goo.gl/example7",
      ultimaSedeAnterior: "San Juan",
      proximaSede: "Neuquén",
      dateTimes: [
        {
          fechaDesde: "2025-05-03",
          fechaHasta: "2025-05-03",
          horaDesde: "21:00",
          horaHasta: "23:00",
        },
        {
          fechaDesde: "2025-05-04",
          fechaHasta: "2025-05-04",
          horaDesde: "19:00",
          horaHasta: "21:00",
        },
      ],
      estimatedAttendance: { local: "250", national: "10", foreign: "5" },
      virtualTransmission: false,
      transmissionLink: null,
      producer: "Grupo Teatral Los Andes",
      website: "https://losteandinos.com.ar",
      logo: "logo_teatro_andes.png",
      image: "/carrouselEvents/lacomediafinal.png",
      responsiveImage: "imagen_obra_teatro_responsive.jpg",
    },
    {
      nombre: "Debate Presidencial - Elecciones 2025",
      numeroEdicion: null,
      descripcion:
        "Debate entre los principales candidatos a la presidencia de la nación.",
      type: "Gubernamentales",
      subtype: "Debate",
      origen: "Gubernamental",
      tema: "Gobierno / Sindical",
      frecuencia: "Unico",
      tipoRotacion: "Nacional",
      mesasCoffeeBreak: false,
      cateringAlmuerzo: false,
      cateringCena: false,
      paquetePreEvento: false,
      paquetePostEvento: false,
      sede: "Estudios de Canal 7",
      ciudad: "Buenos Aires",
      salonesUtilizados: "Estudio Principal",
      mapsUrl: "https://maps.app.goo.gl/example8",
      ultimaSedeAnterior: null,
      proximaSede: null,
      dateTimes: [
        {
          fechaDesde: "2025-05-25",
          fechaHasta: "2025-05-25",
          horaDesde: "20:00",
          horaHasta: "22:00",
        },
      ],
      estimatedAttendance: { local: "100", national: "50", foreign: "10" }, // Principalmente equipo y prensa
      virtualTransmission: true,
      transmissionLink: "https://tvpublica.com.ar/vivo",
      producer: "Cámara Nacional Electoral",
      website: "https://electoralnacional.gob.ar",
      logo: "logo_cne.png",
      // image: "imagen_debate_presidencial.jpg",
      responsiveImage: "imagen_debate_presidencial_responsive.jpg",
    },
    {
      nombre: "Clase Magistral de Cocina Vegana",
      numeroEdicion: "1",
      descripcion:
        "Clase demostrativa y práctica sobre cocina vegana de alta calidad.",
      type: "Otros",
      subtype: "Clase",
      origen: "Empresarial",
      tema: "Gastronomia",
      frecuencia: "Unico",
      tipoRotacion: "Local",
      mesasCoffeeBreak: true,
      cateringAlmuerzo: true,
      cateringCena: false,
      paquetePreEvento: false,
      paquetePostEvento: false,
      sede: "Escuela de Cocina Gourmet",
      ciudad: "San Miguel de Tucumán",
      salonesUtilizados: "Aula de Cocina Principal",
      mapsUrl: "https://maps.app.goo.gl/example9",
      ultimaSedeAnterior: null,
      proximaSede: null,
      dateTimes: [
        {
          fechaDesde: "2025-05-30",
          fechaHasta: "2025-05-30",
          horaDesde: "15:00",
          horaHasta: "19:00",
        },
      ],
      estimatedAttendance: { local: "30", national: "5", foreign: "0" },
      virtualTransmission: false,
      transmissionLink: null,
      producer: "Chef Vegano Sofía Pérez",
      website: "https://sofiaperezvegan.com",
      logo: "logo_sofia_vegan.png",
      // image: "imagen_clase_cocina_vegana.jpg",
      responsiveImage: "imagen_clase_cocina_vegana_responsive.jpg",
    },
    {
      nombre: "Feria de Artesanías Regionales",
      numeroEdicion: "Edición Otoño 2025",
      descripcion:
        "Exposición y venta de artesanías típicas de la región del Noroeste Argentino.",
      type: "Cultura",
      subtype: "Feria Artesanal",
      origen: "Asociativo / Sin fines de lucro",
      tema: "Arte y desenio",
      frecuencia: "Estacional",
      tipoRotacion: "Regional",
      mesasCoffeeBreak: false,
      cateringAlmuerzo: false,
      cateringCena: false,
      paquetePreEvento: false,
      paquetePostEvento: false,
      sede: "Predio Ferial",
      ciudad: "Salta",
      salonesUtilizados: "Pabellón Central, Espacios al Aire Libre",
      mapsUrl: "https://maps.app.goo.gl/example10",
      ultimaSedeAnterior: "Jujuy",
      proximaSede: "Catamarca",
      dateTimes: [
        {
          fechaDesde: "2025-05-01",
          fechaHasta: "2025-05-01",
          horaDesde: "10:00",
          horaHasta: "20:00",
        },
        {
          fechaDesde: "2025-05-02",
          fechaHasta: "2025-05-02",
          horaDesde: "10:00",
          horaHasta: "20:00",
        },
        {
          fechaDesde: "2025-05-03",
          fechaHasta: "2025-05-03",
          horaDesde: "10:00",
          horaHasta: "20:00",
        },
        {
          fechaDesde: "2025-05-04",
          fechaHasta: "2025-05-04",
          horaDesde: "10:00",
          horaHasta: "20:00",
        },
      ],
      estimatedAttendance: { local: "5000", national: "1000", foreign: "50" },
      virtualTransmission: false,
      transmissionLink: null,
      producer: "Asociación de Artesanos del NOA",
      website: "https://artesaniasnoa.com.ar",
      logo: "logo_artesanos_noa.png",
      image: "/carrouselEvents/artesaniasregionales.png",
      responsiveImage: "imagen_feria_artesanias_responsive.jpg",
    },
    {
      nombre: "Simposio Nacional de Energías Renovables",
      numeroEdicion: "VIII",
      descripcion:
        "Encuentro de expertos y empresas del sector de energías renovables para discutir avances y políticas.",
      type: "Asociativos",
      subtype: "Simposio",
      origen: "Academico",
      tema: "Energia",
      frecuencia: "Anual",
      tipoRotacion: "Nacional",
      mesasCoffeeBreak: true,
      cateringAlmuerzo: true,
      cateringCena: false,
      paquetePreEvento: false,
      paquetePostEvento: true,
      sede: "Centro de Convenciones Salta",
      ciudad: "Salta",
      salonesUtilizados: "Salón A, Sala de Conferencias 1 y 2",
      mapsUrl: "https://maps.app.goo.gl/example20",
      ultimaSedeAnterior: "Neuquén",
      proximaSede: "Mendoza",
      dateTimes: [
        {
          fechaDesde: "2025-05-12",
          fechaHasta: "2025-05-12",
          horaDesde: "09:00",
          horaHasta: "18:30",
        },
        {
          fechaDesde: "2025-05-13",
          fechaHasta: "2025-05-13",
          horaDesde: "09:00",
          horaHasta: "18:30",
        },
        {
          fechaDesde: "2025-05-14",
          fechaHasta: "2025-05-14",
          horaDesde: "09:00",
          horaHasta: "18:30",
        },
      ],
      estimatedAttendance: { local: "350", national: "200", foreign: "40" },
      virtualTransmission: true,
      transmissionLink: "https://energiasrenovables.com.ar/live",
      producer: "Cámara Argentina de Energías Renovables",
      website: "https://energiasrenovables.com.ar/simposio2025",
      logo: "logo_caer.png",
      // image: "imagen_simposio_energias.jpg",
      responsiveImage: "imagen_simposio_energias_responsive.jpg",
    },
    {
      nombre: "Reunión de Negocios - Sector Textil",
      numeroEdicion: null,
      descripcion:
        "Encuentro para empresas y proveedores del sector textil para generar nuevas oportunidades de negocio.",
      type: "Corporativos",
      subtype: "Reunión de Negocios",
      origen: "Empresarial",
      tema: "Industrial",
      frecuencia: "Cuatrimestral",
      tipoRotacion: "Regional",
      mesasCoffeeBreak: true,
      cateringAlmuerzo: true,
      cateringCena: false,
      paquetePreEvento: false,
      paquetePostEvento: false,
      sede: "Hotel Catalinas Park",
      ciudad: "San Miguel de Tucumán",
      salonesUtilizados: "Salón de Eventos",
      mapsUrl: "https://maps.app.goo.gl/example21",
      ultimaSedeAnterior: "Santiago del Estero",
      proximaSede: "Jujuy",
      dateTimes: [
        {
          fechaDesde: "2025-05-07",
          fechaHasta: "2025-05-07",
          horaDesde: "10:00",
          horaHasta: "16:00",
        },
      ],
      estimatedAttendance: { local: "80", national: "30", foreign: "5" },
      virtualTransmission: false,
      transmissionLink: null,
      producer: "Cámara de la Industria Textil",
      website: "https://camaratextil.com.ar/reunion-negocios",
      logo: "logo_camara_textil.png",
      image: "/carrouselEvents/reuniondenegocios.png",
      responsiveImage: "imagen_reunion_textil_responsive.jpg",
    },
    {
      nombre: "Exposición de Arte Contemporáneo",
      numeroEdicion: null,
      descripcion:
        "Muestra de obras de artistas contemporáneos locales y nacionales.",
      type: "Cultura",
      subtype: "Exposición de Arte",
      origen: "Asociativo / Sin fines de lucro",
      tema: "Arte y desenio",
      frecuencia: "Irregular",
      tipoRotacion: "Local",
      mesasCoffeeBreak: true,
      cateringAlmuerzo: false,
      cateringCena: false,
      paquetePreEvento: true,
      paquetePostEvento: false,
      sede: "Museo de Bellas Artes",
      ciudad: "Córdoba",
      salonesUtilizados: "Salas 1, 2 y 3",
      mapsUrl: "https://maps.app.goo.gl/example22",
      ultimaSedeAnterior: "Museo de Bellas Artes",
      proximaSede: "Galería de Arte Moderno",
      dateTimes: [
        {
          fechaDesde: "2025-05-17",
          fechaHasta: "2025-05-17",
          horaDesde: "10:00",
          horaHasta: "18:00",
        },
        {
          fechaDesde: "2025-05-18",
          fechaHasta: "2025-05-18",
          horaDesde: "10:00",
          horaHasta: "18:00",
        },
        {
          fechaDesde: "2025-05-19",
          fechaHasta: "2025-05-19",
          horaDesde: "10:00",
          horaHasta: "18:00",
        },
        {
          fechaDesde: "2025-05-20",
          fechaHasta: "2025-05-20",
          horaDesde: "10:00",
          horaHasta: "18:00",
        },
        {
          fechaDesde: "2025-05-21",
          fechaHasta: "2025-05-21",
          horaDesde: "10:00",
          horaHasta: "18:00",
        },
        {
          fechaDesde: "2025-05-22",
          fechaHasta: "2025-05-22",
          horaDesde: "10:00",
          horaHasta: "18:00",
        },
        {
          fechaDesde: "2025-05-23",
          fechaHasta: "2025-05-23",
          horaDesde: "10:00",
          horaHasta: "18:00",
        },
        {
          fechaDesde: "2025-05-24",
          fechaHasta: "2025-05-24",
          horaDesde: "10:00",
          horaHasta: "18:00",
        },
        {
          fechaDesde: "2025-05-25",
          fechaHasta: "2025-05-25",
          horaDesde: "10:00",
          horaHasta: "18:00",
        },
        {
          fechaDesde: "2025-05-26",
          fechaHasta: "2025-05-26",
          horaDesde: "10:00",
          horaHasta: "18:00",
        },
        {
          fechaDesde: "2025-05-27",
          fechaHasta: "2025-05-27",
          horaDesde: "10:00",
          horaHasta: "18:00",
        },
        {
          fechaDesde: "2025-05-28",
          fechaHasta: "2025-05-28",
          horaDesde: "10:00",
          horaHasta: "18:00",
        },
        {
          fechaDesde: "2025-05-29",
          fechaHasta: "2025-05-29",
          horaDesde: "10:00",
          horaHasta: "18:00",
        },
        {
          fechaDesde: "2025-05-30",
          fechaHasta: "2025-05-30",
          horaDesde: "10:00",
          horaHasta: "18:00",
        },
        {
          fechaDesde: "2025-05-31",
          fechaHasta: "2025-05-31",
          horaDesde: "10:00",
          horaHasta: "18:00",
        },
      ],
      estimatedAttendance: { local: "150", national: "20", foreign: "10" },
      virtualTransmission: true,
      transmissionLink: "https://museobba.cba.gov.ar/exposicion-virtual",
      producer: "Asociación de Artistas Visuales",
      website: "https://asociacionartistas.org.ar/expo-mayo",
      logo: "logo_aav.png",
      // image: "imagen_expo_arte.jpg",
      responsiveImage: "imagen_expo_arte_responsive.jpg",
    },
    {
      nombre: "Taller de Desarrollo Web con React",
      numeroEdicion: "4",
      descripcion:
        "Taller práctico para aprender a construir aplicaciones web utilizando la librería React.",
      type: "Académico",
      subtype: "Taller",
      origen: "Empresarial",
      tema: "Tecnologia",
      frecuencia: "Semestral",
      tipoRotacion: "Local",
      mesasCoffeeBreak: true,
      cateringAlmuerzo: true,
      cateringCena: false,
      paquetePreEvento: false,
      paquetePostEvento: false,
      sede: "Academia de Programación Online",
      ciudad: "San Miguel de Tucumán",
      salonesUtilizados: "Aula Virtual 1 y 2",
      mapsUrl: "https://maps.app.goo.gl/example23",
      ultimaSedeAnterior: "Academia de Programación Online",
      proximaSede: "Academia de Programación Online",
      dateTimes: [
        {
          fechaDesde: "2025-05-29",
          fechaHasta: "2025-05-29",
          horaDesde: "14:00",
          horaHasta: "18:00",
        },
        {
          fechaDesde: "2025-05-30",
          fechaHasta: "2025-05-30",
          horaDesde: "14:00",
          horaHasta: "18:00",
        },
      ],
      estimatedAttendance: { local: "40", national: "10", foreign: "2" },
      virtualTransmission: true,
      transmissionLink: "https://academiaonline.com/taller-react",
      producer: "Academia de Programación Online",
      website: "https://academiaonline.com",
      logo: "logo_academia_online.png",
      // image: "imagen_taller_react.jpg",
      responsiveImage: "imagen_taller_react_responsive.jpg",
    },
    {
      nombre: "Carrera de Montaña 'Desafío Andino'",
      numeroEdicion: "VI",
      descripcion:
        "Competencia de trail running en los paisajes de la Cordillera de los Andes.",
      type: "Deporte",
      subtype: "Carrera",
      origen: "Empresarial",
      tema: "Deporte",
      frecuencia: "Anual",
      tipoRotacion: "Regional",
      mesasCoffeeBreak: false,
      cateringAlmuerzo: false,
      cateringCena: true, // Cena de premiación
      paquetePreEvento: true,
      paquetePostEvento: true,
      sede: "Villa Carlos Paz",
      ciudad: "Córdoba",
      salonesUtilizados: "Circuitos de Montaña",
      mapsUrl: "https://maps.app.goo.gl/example24",
      ultimaSedeAnterior: "Bariloche",
      proximaSede: "Mendoza",
      dateTimes: [
        {
          fechaDesde: "2025-05-24",
          fechaHasta: "2025-05-24",
          horaDesde: "08:00",
          horaHasta: "16:00",
        },
      ],
      estimatedAttendance: { local: "200", national: "150", foreign: "50" },
      virtualTransmission: false,
      transmissionLink: null,
      producer: "Andes Adventure Sports",
      website: "https://desafioandino.com",
      logo: "logo_andes_adventure.png",
      // image: "imagen_carrera_montana.jpg",
      responsiveImage: "imagen_carrera_montana_responsive.jpg",
    },
    {
      nombre: "Lanzamiento de Nuevo Producto - Línea de Cosméticos Naturales",
      numeroEdicion: null,
      descripcion:
        "Evento de presentación de la nueva línea de cosméticos elaborados con ingredientes naturales.",
      type: "Corporativos",
      subtype: "Lanzamiento de Producto",
      origen: "Empresarial",
      tema: "Cosmetica y estetica",
      frecuencia: "Unico",
      tipoRotacion: "Nacional",
      mesasCoffeeBreak: true,
      cateringAlmuerzo: true,
      cateringCena: false,
      paquetePreEvento: true,
      paquetePostEvento: true,
      sede: "Hotel Alvear Icon",
      ciudad: "Buenos Aires",
      salonesUtilizados: "Salón Grand Cru",
      mapsUrl: "https://maps.app.goo.gl/example25",
      ultimaSedeAnterior: null,
      proximaSede: null,
      dateTimes: [
        {
          fechaDesde: "2025-05-21",
          fechaHasta: "2025-05-21",
          horaDesde: "11:00",
          horaHasta: "15:00",
        },
      ],
      estimatedAttendance: { local: "100", national: "50", foreign: "20" }, // Influencers, prensa, clientes
      virtualTransmission: true,
      transmissionLink: "https://cosmeticosnaturales.com/lanzamiento",
      producer: "Laboratorios Natural Beauty",
      website: "https://cosmeticosnaturales.com",
      logo: "logo_natural_beauty.png",
      // image: "imagen_lanzamiento_cosmeticos.jpg",
      responsiveImage: "imagen_lanzamiento_cosmeticos_responsive.jpg",
    },
    {
      nombre: "Concierto de Orquesta Sinfónica Provincial",
      numeroEdicion: null,
      descripcion:
        "Presentación de la Orquesta Sinfónica Provincial interpretando obras clásicas.",
      type: "Cultura",
      subtype: "Concierto",
      origen: "Gubernamental",
      tema: "Cultura",
      frecuencia: "Semanal",
      tipoRotacion: "Provincial",
      mesasCoffeeBreak: false,
      cateringAlmuerzo: false,
      cateringCena: false,
      paquetePreEvento: false,
      paquetePostEvento: false,
      sede: "Teatro San Martín",
      ciudad: "San Miguel de Tucumán",
      salonesUtilizados: "Sala Principal",
      mapsUrl: "https://maps.app.goo.gl/example26",
      ultimaSedeAnterior: "Teatro Alberdi",
      proximaSede: "Casa de la Cultura",
      dateTimes: [
        {
          fechaDesde: "2025-05-09",
          fechaHasta: "2025-05-09",
          horaDesde: "20:30",
          horaHasta: "22:30",
        },
      ],
      estimatedAttendance: { local: "500", national: "10", foreign: "5" },
      virtualTransmission: true,
      transmissionLink: "https://orquestasinfonica.tucuman.gov.ar/vivo",
      producer: "Secretaría de Cultura de la Provincia",
      website: "https://orquestasinfonica.tucuman.gov.ar",
      logo: "logo_sinfonica_tucuman.png",
      image: "/carrouselEvents/cosp.jpg",
      responsiveImage: "imagen_concierto_sinfonica_responsive.jpg",
    },
    {
      nombre: "Audiencia Pública - Proyecto de Ley de Desarrollo Urbano",
      numeroEdicion: null,
      descripcion:
        "Sesión para que la ciudadanía exprese sus opiniones sobre el proyecto de ley de desarrollo urbano.",
      type: "Gubernamentales",
      subtype: "Audiencia Pública",
      origen: "Gubernamental",
      tema: "Gobierno / Sindical",
      frecuencia: "Unico",
      tipoRotacion: "Local",
      mesasCoffeeBreak: true,
      cateringAlmuerzo: false,
      cateringCena: false,
      paquetePreEvento: false,
      paquetePostEvento: false,
      sede: "Legislatura Provincial",
      ciudad: "Salta",
      salonesUtilizados: "Salón de Sesiones",
      mapsUrl: "https://maps.app.goo.gl/example27",
      ultimaSedeAnterior: null,
      proximaSede: null,
      dateTimes: [
        {
          fechaDesde: "2025-05-23",
          fechaHasta: "2025-05-23",
          horaDesde: "10:00",
          horaHasta: "14:00",
        },
      ],
      estimatedAttendance: { local: "100", national: "10", foreign: "0" }, // Principalmente ciudadanos interesados y prensa
      virtualTransmission: true,
      transmissionLink: "https://legislaturasalta.gob.ar/envivo",
      producer: "Legislatura de la Provincia de Salta",
      website: "https://legislaturasalta.gob.ar",
      logo: "logo_legislatura_salta.png",
      // image: "imagen_audiencia_publica.jpg",
      responsiveImage: "imagen_audiencia_publica_responsive.jpg",
    },
    {
      nombre: "Evento Benéfico - Cena de Gala",
      numeroEdicion: "V",
      descripcion:
        "Cena de gala para recaudar fondos para la fundación de ayuda a niños.",
      type: "Otros",
      subtype: "Evento Benéfico",
      origen: "Asociativo / Sin fines de lucro",
      tema: "Otros", 
      frecuencia: "Anual",
      tipoRotacion: "Local",
      mesasCoffeeBreak: false,
      cateringAlmuerzo: false,
      cateringCena: true,
      paquetePreEvento: true,
      paquetePostEvento: true,
      sede: "Salón de Fiestas La Fontana",
      ciudad: "Mendoza",
      salonesUtilizados: "Salón Principal",
      mapsUrl: "https://maps.app.goo.gl/example28",
      ultimaSedeAnterior: "Salón de Fiestas Los Olivos",
      proximaSede: "Salón de Fiestas La Fontana",
      dateTimes: [
        {
          fechaDesde: "2025-05-06",
          fechaHasta: "2025-05-06",
          horaDesde: "21:00",
          horaHasta: "00:00",
        },
      ],
      estimatedAttendance: { local: "150", national: "10", foreign: "2" },
      virtualTransmission: false,
      transmissionLink: null,
      producer: "Fundación Sonrisas de Esperanza",
      website: "https://fundacionsonrisas.org.ar/cena-anual",
      logo: "logo_fundacion_sonrisas.png",
      image: "/carrouselEvents/ebcg.jpg",
      responsiveImage: "imagen_cena_benefica_responsive.jpg",
    },
    {
      nombre: "Entrega de Diplomas - Cursos de Capacitación Profesional",
      numeroEdicion: null,
      descripcion:
        "Ceremonia de entrega de diplomas a los alumnos que completaron los cursos de capacitación.",
      type: "Académico",
      subtype: "Entrega de Diplomas",
      origen: "Empresarial",
      tema: "Educacion",
      frecuencia: "Cuatrimestral",
      tipoRotacion: "Local",
      mesasCoffeeBreak: true,
      cateringAlmuerzo: false,
      cateringCena: false,
      paquetePreEvento: false,
      paquetePostEvento: true,
      sede: "Auditorio de la Cámara de Comercio",
      ciudad: "Rosario",
      salonesUtilizados: "Auditorio Principal",
      mapsUrl: "https://maps.app.goo.gl/example29",
      ultimaSedeAnterior: "Auditorio de la Cámara de Comercio",
      proximaSede: "Salón de Actos del Instituto...",
      dateTimes: [
        {
          fechaDesde: "2025-05-31",
          fechaHasta: "2025-05-31",
          horaDesde: "18:00",
          horaHasta: "20:00",
        },
      ],
      estimatedAttendance: { local: "200", national: "5", foreign: "0" }, // Alumnos y familiares
      virtualTransmission: true,
      transmissionLink: "https://camaracomercio.org.ar/entrega-diplomas",
      producer: "Instituto de Capacitación Profesional",
      website: "https://institutoprofesional.com.ar",
      logo: "logo_icp.png",
      // image: "imagen_entrega_diplomas.jpg",
      responsiveImage: "imagen_entrega_diplomas_responsive.jpg",
    },
    {
      nombre: "Evento Semanal de los Lunes",
      numeroEdicion: null,
      descripcion:
        "Este evento se repite todos los lunes del mes de mayo de 2025.",
      type: "Otros", // Puedes cambiar el tipo si es necesario
      subtype: "Evento Semanal", // Puedes cambiar el subtipo si es necesario
      origen: "Otro", // Puedes cambiar el origen si es necesario
      tema: "General", // Puedes cambiar el tema si es necesario
      frecuencia: "Semanal",
      tipoRotacion: "Local",
      mesasCoffeeBreak: false,
      cateringAlmuerzo: false,
      cateringCena: false,
      paquetePreEvento: false,
      paquetePostEvento: false,
      sede: "Lugar por Definir", // Puedes definir la sede
      ciudad: "San Miguel de Tucumán", // Mantengo la ciudad por contexto
      salonesUtilizados: null,
      mapsUrl: null,
      ultimaSedeAnterior: null,
      proximaSede: null,
      dateTimes: [
        {
          fechaDesde: "2025-05-05",
          fechaHasta: "2025-05-05",
          horaDesde: "10:00",
          horaHasta: "11:00",
        },
        {
          fechaDesde: "2025-05-12",
          fechaHasta: "2025-05-12",
          horaDesde: "10:00",
          horaHasta: "11:00",
        },
        {
          fechaDesde: "2025-05-19",
          fechaHasta: "2025-05-19",
          horaDesde: "10:00",
          horaHasta: "11:00",
        },
        {
          fechaDesde: "2025-05-26",
          fechaHasta: "2025-05-26",
          horaDesde: "10:00",
          horaHasta: "11:00",
        },
      ],
      estimatedAttendance: { local: "10", national: "0", foreign: "0" },
      virtualTransmission: false,
      transmissionLink: null,
      producer: null,
      website: null,
      logo: null,
      image: null,
      responsiveImage: null,
    },
  ];

  const [events, setEvents] = useState(initialEvents);

  const addEvent = (newEvent) => {
    setEvents([...events, newEvent]);
  };

  return (
    <EventsContext.Provider value={{ events, addEvent }}>
      {children}
    </EventsContext.Provider>
  );
};
